apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-db
  template:
    metadata:
      labels:
        app: judge0-db
    spec:
      containers:
      - name: judge0-db
        image: postgres:16.2
        envFrom:
            - configMapRef:
                name: judge0-config
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: judge0-secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: judge0-db
spec:
  selector:
    app: judge0-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432